### ISSUE TITLE
Rose pine theme does not work

### ISSUE THREAD

**Issue by ebiscaia** [donniebreve/rose-pine-doom-emacs#1]
Hi mate,

Just wanted to let you know the rose pine main theme does not work because of these lines:

`149    :background (if doom-rose-pine-dawn-brighter-comments (doom-blend teal base 0.07)))`

`174        :foreground (if doom-rose-pine-dawn-brighter-modeline text subtle))`

The solution is to remove the word dawn from these lines.

**Comment by donniebreve** [comment]
Thanks!

**Comment by ebiscaia** [comment]
Just to keep it here, but in line 199 I think you meant rose instead of pink.

Thanks again
